name: Build and publish

on:
  push:
    branches: [ master, mauicompat ]
  pull_request:
    branches: [ master, mauicompat ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install MAUI workload
      run: dotnet workload install maui
    - name: Add GitHub Packages to NuGet
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/emclient/index.json -n github -u emclient -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Build number
      run: echo "Build ${GITHUB_RUN_NUMBER}"
    - name: Build and pack
      run: |
        export JI_JAVA_HOME="$JAVA_HOME_11_X64"
        dotnet build src/Acr.UserDialogs /p:Configuration=Release /p:BUILD_BUILDNUMBER=${GITHUB_RUN_NUMBER} /t:Build,Pack
    - uses: actions/upload-artifact@master
      with:
        name: build-artifacts
        path: src/Acr.UserDialogs/bin

  publish:
    permissions:
      packages: write
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - uses: actions/download-artifact@master
      with:
        name: build-artifacts
        path: src/Acr.UserDialogs/bin
    - name: Publish
      if: ${{ github.event_name == 'push' }}
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/emclient/index.json -n github
        find src/Acr.UserDialogs/bin/Release -name '*.nupkg' | xargs -i dotnet nuget push {} -s github --api-key ${{ secrets.GITHUB_TOKEN }}
