name: Build and publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build
      run: msbuild src/Acr.UserDialogs /p:Configuration=Release /restore
    - name: Pack
      run: msbuild src/Acr.UserDialogs /p:Configuration=Release /t:Pack
    - uses: actions/upload-artifact@master
      with:
        name: build-artifacts
        path: src/Acr.UserDialogs/bin

  publish:
    permissions:
      packages: write
    needs: build
    runs-on: windows-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: actions/download-artifact@master
      with:
        name: build-artifacts
        path: src/Acr.UserDialogs/bin
    - name: Publish
      # if: ${{ github.event_name == 'push' }}
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/emclient/index.json -n github
        dotnet nuget push src/Acr.UserDialogs/bin/Release/*.nupkg -s github --api-key ${{ secrets.GITHUB_TOKEN }}
